name: investimize
channels:
 - http://conda.anaconda.org/mathieu
dependencies:
# - appnope=0.1.0=py35_0
- beautifulsoup4=4.4.1=py35_0
- cbc
- cycler=0.9.0=py35_0
- decorator=4.0.6=py35_0
- freetype=2.5.5=0
- html5lib=0.999=py35_0
- ipykernel=4.1.1=py35_0
- ipython=4.0.1=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=4.1.0=py35_0
- jinja2=2.8=py35_0
- jsonschema=2.4.0=py35_0
- jupyter=1.0.0=py35_1
- jupyter_client=4.1.1=py35_0
- jupyter_console=4.0.3=py35_0
- jupyter_core=4.0.6=py35_0
- libpng=1.6.17=0
- libxml2=2.9.2=0
- libxslt
- lxml=3.5.0=py35_0
- markupsafe=0.23=py35_0
- matplotlib=1.5.0=np110py35_0
- mistune=0.7.1=py35_0
- nbconvert=4.1.0=py35_0
- nbformat=4.0.1=py35_0
- notebook=4.0.6=py35_0
- numpy=1.10.2=py35_0
- openssl=1.0.2d=0
- pandas=0.17.1=np110py35_0
- path.py=8.1.2=py35_1
- pexpect=3.3=py35_0
- pickleshare=0.5=py35_0
- pip=7.1.2=py35_0
- ptyprocess=0.5=py35_0
- py=1.4.30=py35_0
- pygments=2.0.2=py35_0
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_1
- pytest=2.8.1=py35_0
- python=3.5.1=0
- python-dateutil=2.4.2=py35_0
# - python.app=1.2=py35_4
- pytz=2015.7=py35_0
- pyzmq=15.1.0=py35_0
- qt=4.8.7=1
- qtconsole=4.1.1=py35_0
- readline=6.2=2
- requests=2.9.0=py35_0
- scipy
- setuptools=19.1.1=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- sqlite=3.8.4.1=1
- terminado=0.5=py35_1
- tk=8.5.18=0
- tornado=4.3=py35_0
- traitlets=4.0.0=py35_0
- wheel=0.26.0=py35_1
- xz=5.0.5=0
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - boto3==1.2.3
  - botocore==1.3.14
  - docutils==0.12
  - fake-useragent==0.0.8
  - ipython-genutils==0.1.0
  - jmespath==0.9.0
  - jupyter-client==4.1.1
  - jupyter-console==4.0.3
  - jupyter-core==4.0.6
  - lz4
  - tqdm==3.4.0
  - Flask==0.10.1
  - flask-restful==0.3.5
  - uwsgi
  - connexion

